### PR TITLE
feat: Add a jared.md

### PR DESCRIPTION
**Pull request by jkohrt7**
### Description
- Added a markdown file with some info about me & some icebreakers.

#### To Validate
  1. Make sure all GitHub action PR checks have passed.
  2. Pull down all related branches.  
  3. Check spelling, ~~grammer~~ grammar.

### CODE REVIEW

**Review by tisidro — CHANGES_REQUESTED** [review]
Looks great overall Jared! One small change to line 5, I suggest deleting the first sentence as it repeats the second/is incomplete. 
Screen Shot 2022-07-25 at 10 37 07 AM

**Comment by jkohrt7** [comment]
> Looks great overall Jared! One small change to line 5, I suggest deleting the first sentence as it repeats the second/is incomplete.
> Screen Shot 2022-07-25 at 10 37 07 AM

Should be fixed now! Thanks for the suggestion.

**Comment by jordanleven** [comment]
> Looks great overall Jared! One small change to line 5, I suggest deleting the first sentence as it repeats the second/is incomplete.
> Screen Shot 2022-07-25 at 10 37 07 AM

Hey @tisidro  - don't forget that you can comment directly on lines in the PR instead of posting screenshots of the code.

**Comment by jkohrt7** [comment]
The force commit was to squash the commit history.

**Review by tisidro — APPROVED** [review]
Thanks for making those changes!

**Review by tisidro — APPROVED** [review]

**Comment by jordanleven** [comment]
Hey @jkohrt7 — some feedback on your commit message:

> Fix:
> - Included some icebreakers, basic info in a markdown file.

Since this isn't fixing unexpected behavior, I'm not sure this would qualify as a fix.

> Closes FSA22V2-39
> 
> fix: Grammar issue on line 5
> 
> Issue: there was a sentence fragment on line 5.
> 
> Fix:
> - deleted the sentence fragment
Since these are fixing issues that were both caused and addressed in a single PR, I'm not sure we need a record of them in your commit message — especially since, when squashing, all references to these issues are removed. Think back to the discussion last week about the commit message and the contextual change after commits are squashed and merged into the production branch.

**Review by tisidro — APPROVED** [review]

**Review by tisidro — APPROVED** [review]

**Pull request merged**
